### ISSUE TITLE
Number of senses per entry (having at least one sense for every entry)

### ISSUE THREAD

**Issue by sbyim** [elexis-eu/edie#1]

**Comment by sbyim** [comment]
@jmccrae
for this issue we would need a GET endpoint for multiple entries.
dictionary service only has an endpoint to retrieve a single entry by ID.
https://elexis-eu.github.io/elexis-rest/#operation/getEntryById

**Comment by jmccrae** [comment]
Not sure I understand. You only need to examine a single entry at a time to evaluate this right? Moreover, you can just call the `getEntryById` repeatedly to get multiple entries, right?

**Comment by sbyim** [comment]
Don't we want to calculate aggregate metrics over all entries? 
If yes, going through all the entries and calling the getEntryById seems extremely inefficient way to do it..
I would expect an endpoint like getAllLemmas with pagination.

**Comment by jmccrae** [comment]
I find REST calls are surprisingly efficient and pagination is harder than it seems. So this may be a case where we avoid premature optimization.

**Comment by sbyim** [comment]
hmmm usually lots of servers often has limitations for such calls in loop, and calls over networks are always are potential perfomance bottleneck.
But i always agree that premature optimization is not the way to go, so let's do it with the loop and see
