### ISSUE TITLE
Types/Numbers dictionaries formats

### ISSUE THREAD

**Issue by sbyim** [elexis-eu/edie#13]

**Comment by sbyim** [comment]
@jmccrae The formats of dictionaries(entries) can be retrieved with <code>/list</code> endpoint, which lists all entries of a dictionary. Doesn't it make more sense to return the <code>formats</code> data as part of dictionary metadata instead of entries, or am i missing something?

**Comment by jmccrae** [comment]
I guess it may be more straightforward, but I guess we wanted to support dictionaries that have only been partially converted to RDF or JSON. I wouldn't see any critical reason to change this at this point
